// Componentes partilhados da v2 (plano §F.3) — importar daqui: import { Button, Sheet } from '../../ui'
export { default as Icon } from './Icon.jsx'
export { ICONS, categoryIcon } from './icons.js'
export { default as Button } from './Button.jsx'
export { default as IconButton } from './IconButton.jsx'
export {
  default as Field, useField, TextInput, MoneyInput, DateInput, TimeInput, TextArea, SearchInput, Select,
  parseMoney, moneyInputValue,
} from './Field.jsx'
export { default as Switch } from './Switch.jsx'
export { default as Segmented } from './Segmented.jsx'
export { default as Chip, ChipRow, ChipGroup, ProjectChips } from './Chip.jsx'
export { default as Dot } from './Dot.jsx'
export { default as ProjectAvatar } from './ProjectAvatar.jsx'
export { default as StatusBadge, ReceiptMark, Badge } from './StatusBadge.jsx'
export { EventRow, GoogleRow, ExpenseRow, SettingsRow, TaskRow } from './Row.jsx'
export { default as GroupHeader, eventsSummary } from './GroupHeader.jsx'
export { default as Card } from './Card.jsx'
export { default as HeroNumber } from './HeroNumber.jsx'
export { default as Kpi, Delta } from './Kpi.jsx'
export { default as Progress } from './Progress.jsx'
export { default as Callout } from './Callout.jsx'
export { default as SyncBanner, SyncLine, syncTime } from './SyncBanner.jsx'
export { default as EmptyState } from './EmptyState.jsx'
export { default as Skeleton } from './Skeleton.jsx'
export { default as Sheet, useSheet, discardText } from './Sheet.jsx'
export { default as ConfirmDialog, useConfirm, confirmDialog } from './ConfirmDialog.jsx'
export { default as Menu } from './Menu.jsx'
export { ToastProvider, useToast } from './Toast.jsx'
export { default as Attachments, PendingAttachments, useAttachmentUrl } from './Attachments.jsx'
export { default as AttachmentViewer } from './AttachmentViewer.jsx'
export { default as NewKindSwitch } from './NewKindSwitch.jsx'
export { default as TopBar, Avatar, AvatarButton } from './TopBar.jsx'
export { useReducedMotion, useLocalPref, useScrollRestore, useVisualViewport, useMediaQuery, TEXT_SCALES, applyTextScale } from './hooks.js'
